---
output:
  pdf_document: default
  html_document: default
---


## Module 6 - The TransportationModel

## Purpose 

## The purpose of this assignment is to formulate and solve a transportation / transhipment problem. 

## In addition, this will help you master the following module outcomes:
## • Formulate a transportation problem. 
## • Solve a transportation problem.

## Directions

## Heart Start produces automated external defibrillators (AEDs) in each of two different plants (A and B). The unit production costs and monthly production capacity of the two plants are indicated in the table below. The AEDs are sold through three wholesalers. The shipping cost from each plant to the warehouse of each wholesaler along with the monthly demand from each wholesaler are also indicated in the table. How many AEDs should be produced in each plant, and how should they be distributed to each of the three wholesaler warehouses so as to minimize 
the combined cost of production and shipping?


```{r}
# Load the lpSolve library
library(lpSolve)

# Define the cost matrix
cost_matrix <- matrix(c(22, 14, 30, 16, 20, 24), nrow = 2, byrow = TRUE)

# Define the production capacity for each plant
production_capacity <- c(100, 120)

# Define the demand for each warehouse
demand <- c(80, 60, 70)

# Solve the transportation problem
solution <- lp(direction = "min",
               objective.in = c(cost_matrix),
               const.mat = rbind(diag(2), matrix(1, nrow = 3, ncol = 2)),
               const.dir = c(rep("<=", 2), rep("=", 3)),
               const.rhs = c(production_capacity, demand))

# Extract the solution
optimal_solution <- solution$solution

# Print the optimal solution
print(optimal_solution)

# Print the minimum cost
min_cost <- solution$objval
print(min_cost)

```
